---
title: "NYC Restaurant Inpsection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```


```{r}
data("rest_inspec")


#Chart A
pizza_bagel_df <-
  rest_inspec |> 
  select(cuisine_description, boro, grade, score, latitude, longitude) |> 
  filter(
    str_detect(cuisine_description, "[Pp][Ii][Zz][Zz][Aa]") | 
    str_detect(cuisine_description, "[Bb][Aa][Gg][Ee][Ll]")
    ) |>
  drop_na() 


# Chart B
inspec_score_df <- 
  rest_inspec |> 
  select(boro, score, critical_flag) |> 
  filter(
    boro != "0", 
    score >= 2, 
    critical_flag == "Y") |> 
  drop_na()


# Chart C
grade_boro_df <- 
  rest_inspec |> 
  select(boro, grade) |> 
  drop_na() |> 
  filter(
    grade == "A", 
    boro != "0") |> 
  count(boro) 
```


Column {data-width=650}
-----------------------------------------------------------------------

### Food Inspection Grades and Scores of Pizza and Bagel Spots in NYC

```{r}
pizza_bagel_df |> 
  filter(
    grade == c("A", "B", "C"),
    longitude != 0, 
    latitude != 0) |> 
  mutate(
    label = str_c("Inspection Grade:", grade, "\nInspection Score:", score)
  ) |> 
  plot_ly(
    x = ~longitude, y = ~latitude, type = "scatter", mode = "markers", 
    symbol = ~cuisine_description, color = ~grade , 
    text = ~label, alpha = 0.5, colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Distribution of Restaurant Inspection Scores by NYC Bourough 

```{r}
inspec_score_df |> 
  mutate(
    boro = fct_reorder(boro, score)
  ) |> 
  plot_ly(
    x = ~boro, y = ~score, color = ~boro, 
    type = "box", colors = "viridis"
  )
```

### Count of Restaurants with 'A' Inspection Grades by NYC Bourough

```{r}
grade_boro_df |> 
  mutate(
    boro = fct_reorder(boro, n)
    ) |> 
  plot_ly(
    x = ~boro, y = ~n, color = ~boro,
    type = "bar", colors = "viridis"
    )
```

